<?php

/**
 * @file
 * Contains node_restricted_access.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function node_restricted_access_help($route_name, RouteMatchInterface $arg) {
  switch ($route_name) {
    // Main module help for the node_restricted_access module.
    case 'help.page.node_restricted_access':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the ability to restrict node access based on permission') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_node_access_records().
 */
function node_restricted_access_node_access_records(NodeInterface $node) {
  $grants = [];
  if ($node->hasField('field_restricted_access') && $node->field_restricted_access->value == 1) {
    $grants[] = array(
      'realm' => 'node_restricted_access',
      'gid' => 0,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'langcode' => 'en',
    );
  }
  return $grants;
}

/**
 * Implements hook_node_grants().
 */
function node_restricted_access_node_grants(AccountInterface $account, $op) {
  $grants = [];
  if ($op == 'view') {
    if ($account->hasPermission('view restricted content')) {
      $grants['node_restricted_access'][] = 0;
      return $grants;
    }
  }
  return $grants;
}
